# Generated by Django 2.2.20 on 2021-04-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_auto_20180628_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'get_latest_by': 'modified'},
        ),
    ]
