# Generated by Django 2.2.20 on 2021-04-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0007_auto_20191115_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='refundline',
            options={'get_latest_by': 'modified'},
        ),
    ]
